---
format: revealjs
---

## Today's Agenda {background-image="Images/background-data_blue_v3.png" .center}

```{r}
library(tidyverse)
library(readxl)
library(kableExtra)
library(modelsummary)
```

<br>

::: {.r-fit-text}

**Setting up our Class Project**

- Select the outcome to describe and explain

:::

<br>

::: r-stack
Justin Leinaweaver (Spring 2025)
:::

::: notes
Prep for Class

1. Review Canvas submissions

2. Class CANNOT pick last year's data project: CINC National Power, also note two years ago they did the Gender Inequality Index

<br>

Big day today!

- We need to pick the project that will serve as our focus for the rest of the semester.
:::




## {background-image="Images/background-data_blue_v3.png" .center}

::: {.r-fit-text}
**For Today: Find an Interesting Outcome to Explain**
:::

<br>

Pick **ONE** variable from **ONE** dataset that you think would be a good outcome to explain in our class research project.

- Specify the dataset, the concept, and the specific variable(s)

- Why would this make an interesting outcome to explain?

::: notes

Alright, today you'll take turns pitching us on your proposals

- At the end we'll choose one (or merge a few) and that will be our primary focus for the term

<br>

**Questions before we start?**

- Let's go!

- *ON BOARD: Build a topic list to refer back to*

<br>

*Make sure by the end of class we have:*

- A draft research question

- A data project for the outcome with a shared link to the codebook

- A first choice of variable that measures the outcome of our project
:::




## {background-image="Images/background-data_blue_v3.png" .center}

::: {.r-fit-text}
**For Next Class: Analyzing the First Codebook**
:::

<br>

1. Analyzing the Data Project Overall

    - What are the strengths and weaknesses of the overall data project? What variables should we consider using?
    
2. Analyzing the Selected Outcome 

    - What are the strengths and weaknesses of the specific variable we have chosen as our key outcome to explain? 

::: notes

For Monday we all need to analyze the Codebook!

- The prompts are a little more detailed on Canvas, but these are the general ideas

<br>

**Any questions on the assignment?**

:::