---
format: revealjs
---

## Today's Agenda {background-image="Images/background-data_blue_v3.png" .center}

```{r}
library(tidyverse)
library(readxl)
library(kableExtra)
library(modelsummary)
```

<br>

**Build the First Report**

- Section 3: Univariate Analyses (Current)

<br>

::: r-stack
Justin Leinaweaver (Spring 2025)
:::

::: notes
Prep for Class

1. Make sure all data and the assignment is available on Canvas

2. Post Section 3 assignment details on Canvas (including indicator assignment to students)

<br>

This week we finish up your first report!
:::




## Report 1 {background-image="Images/background-slate_v2.png" .center}

**Analyzing our Outcome Variable(s)**

<br>

1. Due Feb 23rd (Canvas "Assignments")

2. PDFs only

3. Support ALL claims with evidence
    - APA formatted in-text citations
    - APA formatted bibliography

::: notes

Ok, this week we work on your first report.

- Here are the basic requirements.

- Late penalty (-10) points per day

:::



## Report 1 {background-image="Images/background-slate_v2.png" .center}

**Analyzing our Outcome Variable(s)**

<br>

1. Why is this project important?

2. How confident should we be in the methodology?

3. What do the measures currently show us?

4. How are these measures changing across time?

::: notes

As we discussed in week 3, the report is in four sections, each making a separate argument

<br>

Usefully, and I hope you took good notes, we worked on Sections 1 and 2 in class during week 3!

- Made some excellent points that week as I recall!

- Big picture notes on the Canvas assignment itself

<br>

Plan of Attack for this week:

- Today we'll work on the univariate analyses for Section 3

- Wednesday we'll work on the univariate analyses for Section 4.

- Friday we'll finish it all up, writing workshop style

<br>

**SLIDE**: For Section 3 I will ask you to do two things
:::



## Section 3 {background-image="Images/background-slate_v2.png" .center}

**What do the measures currently show us?**

<br>

1. Analyze the current distribution of the `Total` index score

2. Analyze the current distribution of one of the indicators in the dataset (assigned)

::: notes

Two big picture tasks in this section of the paper

- Each of you will "analyze" two variables in the dataset

- This means making an argument about what we learn from applying statistical tools to this data

<br>

I will assign you your indicator

- I'm trying to avoid overlap as much as possible

<br>

**SLIDE**: The evidence needed
:::


## Section 3 {background-image="Images/background-slate_v2.png" .center}

**What do the measures currently show us?**

<br>

1. Analyze the current distribution of the `Total` index score

2. Analyze the current distribution of one of the indicators in the dataset

<br>

**Each variable requires a histogram, descriptive statistics and country examples for context**

::: notes
**Any questions on Section 3?**

- Let's get to work!

<br>

*If people messing around or done early make sure they are available to help others in class, OR have polished their own figures, OR have started writing!*
:::
