---
format: revealjs
---

## Today's Agenda {background-image="Images/background-data_blue_v4.png" .center}

```{r}
library(tidyverse)
library(readxl)
library(kableExtra)
library(modelsummary)
```

<br>

**What do we learn about the world from analyzing the Press Freedom Index produced by Reporters Without Borders?**

- Planning your Analyses for Premises 3 and 4

<br>

::: r-stack
Justin Leinaweaver (Spring 2025)
:::

::: notes
Prep for Class

1. Check Canvas submissions

<br>

This week we finish up your first report!
:::




## {background-image="Images/background-data_blue_v4.png" .center}

::: {.r-fit-text}
**Report 1**

**Analyzing our Outcome Variable(s)**
:::

<br>

1. COMPLETED draft due Feb 21st

2. PDFs only

3. Support ALL claims with evidence
    - APA formatted in-text citations
    - APA formatted bibliography
    
::: notes

Ok, this week we work on your first report.

- Here are the basic requirements.

- Late penalty (-10) points per day

:::



## Report 1 {background-image="Images/background-data_blue_v4.png" .center}

<br>

**What do we learn about the world from analyzing the Press Freedom Index produced by Reporters Without Borders?**

<br>

The reader of your report is a non-expert in data analysis and is not familiar with this particular project, but is very interested in the topic. 

::: notes

**Any questions on the big picture framing of your report?**

:::




## Report 1 {background-image="Images/background-data_blue_v4.png" .center}

<br>

**What do we learn about the world from analyzing the Press Freedom Index produced by Reporters Without Borders?**

1. The importance of the project in the real-world,
2. The key contributors of uncertainty in the project's data,
3. What we learn about the current world from analyzing the most recently available data, and
4. What we learn about the trajectory of press freedom in the world from analyzing the data across time

::: notes

Your report must have a clear macro structure (e.g. intro, body and conclusion)

<br>

The body of your report should be organized around these four premises

- Each premise requires you to make an argument that is clearly explained and supported by evidence

<br>

In terms of evidence:

- Section 1 requires outside evidence for your claims

- Section 2 should be rooted in the methodological material provided by RSF

- Section 3 must include more than one visualization AND descriptive statistics

- Section 4 must include more than one visualization AND descriptive statistics

<br>

**Any questions on the report?**

<br>

At this point we've spent time in class developing your notes and analyses on Sections 1 and 2

- You should have tons of good material on those.

<br>

Today we'll work together to brainstorm the analyses you want to consider for the paper and then start making stuff.

- Wednesday the plan is to work together on analyzing the data

- Friday is then for choosing the analyses you want to include in the paper and polishing them

<br>

**Questions on the plan?**

<br>

**SLIDE**: Let's brainstorm!
:::




## Report 1 {background-image="Images/background-data_blue_v4.png" .center}

**What do we learn about the world from analyzing the Press Freedom Index produced by Reporters Without Borders?**

<br>

### **Premise 3**

- **What do we learn about the current world from analyzing the most recently available data?**

    - All indicators (2024)

::: notes

Ok everybody, let's build a big list of ideas that could help us answer this question

- So, focused on the 2024 data, what specific visualizations or descriptive statistics could we make?

<br>

*ON BOARD: Make a table*

- Columns: `Global` and the five sub indicators (Political, Economic, Legislative, Sociocultural, Security)

- Rows: Histogram, Box plot, Mean, SD, Min, Max

<br>

**SLIDE**: Alright now let's do Premise 4

:::



## Report 1 {background-image="Images/background-data_blue_v4.png" .center}

**What do we learn about the world from analyzing the Press Freedom Index produced by Reporters Without Borders?**

<br>

### **Premise 4**

- **What do we learn about the trajectory of press freedom in the world from analyzing the data across time?**

    - All indicators (2022-2024)
    
    - Global index (2015-2024)

::: notes

Ok everybody, let's build a big list of ideas that could help us answer this question

- So, focused on the 2024 data, what specific visualizations or descriptive statistics could we make?

<br>

*ON BOARD: Make a table*

1. Distributions

    - Histogram snapshots: Global in 2015 and 2024
    
    - Box plot snapshots: Global in 2015 and 2024
    
    - The sub indicators (Political, Economic, Legislative, Sociocultural, Security) histogram snapshots in 2022 and 2024

2. Country observations

    - Individual country line plots across time (find us a country with lots of variation across time!)

<br>

**SLIDE**: There's our plan, let's get to work!

:::




## Next Class {background-image="Images/background-data_blue_v4.png" .center}

<br>

::: {.r-fit-text}

**Outline your Planned Analyses**

1. Build all of the brainstormed analyses

2. Reflect on what you've built, and

3. Submit to Canvas your plan for Premises 3 and 4

:::

::: notes

Submit your plan to Canvas!

<br>

Canvas Assignment: Outline your Planned Analyses

Submit to Canvas a DESCRIPTION (not the actual visualizations or results) of the components you plan to include in your report.

1. What are the specific visualizations and descriptive statistics you plan on including in Premise 3 of your report? Explain EACH and the WHY you are choosing to include these tools.

2. What are the specific visualizations and descriptive statistics you plan on including in Premise 4 of your report? Explain EACH and the WHY you are choosing to include these tools.





:::

