---
format: revealjs
---

## Today's Agenda {background-image="Images/background-data_blue_v4.png" .center}

```{r}
library(tidyverse)
library(readxl)
library(kableExtra)
library(modelsummary)
```

<br>

**What do we learn about the world from analyzing the Press Freedom Index produced by Reporters Without Borders?**

- Refining your Analyses for Premises 3 and 4

<br>

::: r-stack
Justin Leinaweaver (Spring 2025)
:::

::: notes
Prep for Class

1. Check Canvas submissions

<br>

This week we finish up your first report!

:::



## {background-image="Images/background-data_blue_v4.png" .center}

::: {.r-fit-text}
**Report 1**

**Analyzing our Outcome Variable(s)**
:::

<br>

1. COMPLETED draft due Feb 21st

2. PDFs only

3. Support ALL claims with evidence
    - APA formatted in-text citations
    - APA formatted bibliography
    
::: notes

Ok, this week we work on your first report.

- Here are the basic requirements.

- Late penalty (-10) points per day

:::



## Report 1 {background-image="Images/background-data_blue_v4.png" .center}

<br>

**What do we learn about the world from analyzing the Press Freedom Index produced by Reporters Without Borders?**

<br>

The reader of your report is a non-expert in data analysis and is not familiar with this particular project, but is very interested in the topic. 

::: notes

**Any questions on the big picture framing of your report?**

:::




## Report 1 {background-image="Images/background-data_blue_v4.png" .center}

<br>

**What do we learn about the world from analyzing the Press Freedom Index produced by Reporters Without Borders?**

1. The importance of the project in the real-world,
2. The key contributors of uncertainty in the project's data,
3. What we learn about the current world from analyzing the most recently available data, and
4. What we learn about the trajectory of press freedom in the world from analyzing the data across time

::: notes

Your report must have a clear macro structure (e.g. intro, body and conclusion)

<br>

The body of your report should be organized around these four premises

- Each premise requires you to make an argument that is clearly explained and supported by evidence

<br>

In terms of evidence:

- Section 1 requires outside evidence for your claims

- Section 2 should be rooted in the methodological material provided by RSF

- Section 3 must include more than one visualization AND descriptive statistics

- Section 4 must include more than one visualization AND descriptive statistics

<br>

**Any questions on the report?**

<br>

**SLIDE**: Our work last class
:::



## Report 1 {background-image="Images/background-data_blue_v4.png" .center}

<br>

**Premise 3**

- What do we learn about the current world from analyzing the most recently available data?

**Premise 4**

- What do we learn about the trajectory of press freedom in the world from analyzing the data across time?**

::: notes

Last class we brainstormed the analyses we wanted to consider for your reports

<br>

And for today I asked each of you to submit your proposed choices

- e.g. the data tools you planned to use to support your arguments in premises 3 and 4

<br>

Your job today is to:

1. Check in with everybody else in class and here what they learned from the analyses and what they proposed to use in the report 3, and

2. To get to work!

<br>

**SLIDE**: For next class!

:::



## Next Class {background-image="Images/background-data_blue_v4.png" .center}

<br>

**Progress Report**

Submit to Canvas one of the **completely polished visualizations** you intend to use in your report for EACH of Premise 3 and Premise 4.

- e.g. Submit TWO visualizations

::: notes

Canvas Assignment: Progress Report

Submit to Canvas one of the completely polished visualizations you intend to use in your report for EACH of Premise 3 and Premise 4 (two total visualizations).

- Each visualization should be ready for a professional audience (e.g. informative title, clear axis labels, a figure caption and some effort on the plot to provide analyses like benchmarks, observation flags or colors that provide meaning).

:::

