---
format: revealjs
---

## Today's Agenda {background-image="Images/background-data_blue_v4.png" .center}

```{r}
library(tidyverse)
library(readxl)
library(kableExtra)
library(modelsummary)
```

<br>

**What do we learn about the world from analyzing the Press Freedom Index produced by Reporters Without Borders?**

- Premise 4: Focusing on the trends across time

<br>

::: r-stack
Justin Leinaweaver (Spring 2025)
:::

::: notes
Prep for Class

1. TBD

<br>

This week we finish up your first report!

:::



## {background-image="Images/background-data_blue_v4.png" .center}

::: {.r-fit-text}
**Report 1**

**Analyzing our Outcome Variable(s)**
:::

<br>

1. COMPLETED draft due Feb 21st

2. PDFs only

3. Support ALL claims with evidence
    - APA formatted in-text citations
    - APA formatted bibliography
    
::: notes

Ok, this week we work on your first report.

- Here are the basic requirements.

- Late penalty (-10) points per day

:::



## Report 1 {background-image="Images/background-data_blue_v4.png" .center}

<br>

**What do we learn about the world from analyzing the Press Freedom Index produced by Reporters Without Borders?**

<br>

The reader of your report is a non-expert in data analysis and is not familiar with this particular project, but is very interested in the topic. 

::: notes

**Any questions on the big picture framing of your report?**

:::




## Report 1 {background-image="Images/background-data_blue_v4.png" .center}

<br>

**What do we learn about the world from analyzing the Press Freedom Index produced by Reporters Without Borders?**

1. The importance of the project in the real-world,
2. The key contributors of uncertainty in the project's data,
3. What we learn about the current world from analyzing the most recently available data, and
4. What we learn about the trajectory of press freedom in the world from analyzing the data across time

::: notes

As we've discussed previously:

- Your report must have a clear macro structure and, I suggest, a meso structure that mirrors these four required elements. 

- Each of the required elements should be fully explained, all claims should be supported by evidence, and your report should offer the reader your critical analysis of that element.

    - Section 1 requires outside evidence for your claims

    - Section 2 should be rooted in the methodological material provided by RSF

    - Section 3 must include multiple visualizations and descriptive statistics

    - Section 4 must include multiple visualizations and descriptive statistics

<br>

Today we'll focus on Section 4 (brainstorming and making stuff)

<br>

**SLIDE**: Let's zoom in on premise 4 today
:::



## Report 1 {background-image="Images/background-data_blue_v4.png" .center}

**What do we learn about the world from analyzing the Press Freedom Index produced by Reporters Without Borders?**

<br>

### **Premise 4**

- **What do we learn about the trajectory of press freedom in the world from analyzing the data across time?**

::: notes

Ok everybody, let's build a big list of ideas that could help us answer this question

- So, focused on the 2024 data, what specific visualizations or descriptive statistics could we make?

<br>

*ON BOARD: Make a table*

1. Distributions

    - Histogram snapshots: Global in 2015 and 2024
    
    - Box plot snapshots: Global in 2015 and 2024
    
    - The sub indicators (Political, Economic, Legislative, Sociocultural, Security) histogram snapshots in 2022 and 2024

2. Country observations

    - Individual country line plots across time (find us a country with lots of variation across time!)

<br>

There's our plan, let's get to work!

:::

