---
format: revealjs
---

## Today's Agenda {background-image="Images/background-data_blue_v4.png" .center}

```{r}
library(tidyverse)
library(readxl)
library(kableExtra)
library(modelsummary)
```

<br>

**What do we learn about the world from analyzing the Press Freedom Index produced by Reporters Without Borders?**

- Finish and submit the first report

<br>

::: r-stack
Justin Leinaweaver (Spring 2025)
:::

::: notes
Prep for Class

1. Check Canvas submissions
:::



## {background-image="Images/background-data_blue_v4.png" .center}

::: {.r-fit-text}
**Report 1**

**Analyzing our Outcome Variable(s)**
:::

<br>

1. COMPLETED draft due Feb 21st

2. PDFs only

3. Support ALL claims with evidence
    - APA formatted in-text citations
    - APA formatted bibliography
    
::: notes

Ok, today's the big day.

- **How are we doing?**

:::



## Report 1 {background-image="Images/background-data_blue_v4.png" .center}

<br>

**What do we learn about the world from analyzing the Press Freedom Index produced by Reporters Without Borders?**

<br>

The reader of your report is a non-expert in data analysis and is not familiar with this particular project, but is very interested in the topic. 

::: notes

**Any questions on the big picture framing of your report?**

:::




## Report 1 {background-image="Images/background-data_blue_v4.png" .center}

<br>

**What do we learn about the world from analyzing the Press Freedom Index produced by Reporters Without Borders?**

1. The importance of the project in the real-world,
2. The key contributors of uncertainty in the project's data,
3. What we learn about the current world from analyzing the most recently available data, and
4. What we learn about the trajectory of press freedom in the world from analyzing the data across time

::: notes

**Any questions on the assignment's key premises?**

<br>

Ok, class today is reserved for you to work, so let's get to it!

:::
