---
format: revealjs
---

## Today's Agenda {background-image="libs/Images/background-data_blue_v3.png" .center}

```{r}
library(tidyverse)
library(readxl)
library(kableExtra)
library(modelsummary)
```

<br>

**Finish the First Report**

<br>

::: r-stack
Justin Leinaweaver (Spring 2024)
:::

::: notes
Prep for Class

1. TBD
:::


## Report 1 {background-image="libs/Images/background-slate_v2.png" .center}

**Analyzing our Outcome Variable(s)**

<br>

1. Due Feb 23rd (Canvas "Assignments")

2. PDFs only

3. Support ALL claims with evidence
    - APA formatted in-text citations
    - APA formatted bibliography

::: notes

Today we keep wrap-up your first reports.

- Late submissions -10 per day

- All visualizations must be polished

<br>

### Any questions on the assignment in big picture?
:::



## Report 1 {background-image="libs/Images/background-slate_v2.png" .center}

**Analyzing our Outcome Variable(s)**

<br>

1. Why is this project important?

2. How confident should we be in the methodology?

3. What do the measures currently show us?

4. How are these measures changing across time?

::: notes

You have all of class today to work!

<br>

**SLIDE for end of class**: Monday we pick the predictors for our project!
:::




## For Next Class {background-image="libs/Images/background-slate_v2.png" .center}

<br>

We select the predictor for our research project

- e.g. what measures do we want to use to explain the variation in state fragility?

::: notes

Our next job is to select a data project that will give us the predictor(s) for our research project.

- In other words, what do we want to use to explain the variation in the Fragile States Index? 
:::

