---
format: revealjs
---

## Today's Agenda {background-image="Images/background-data_blue_v4.png" .center}

```{r}
#  background-size="1920px 1080px"
library(tidyverse)
library(readxl)
```

<br>

::: {.r-fit-text}

**Selecting the research question for our project**

:::

<br>

::: r-stack
Justin Leinaweaver (Spring 2025)
:::

::: notes
Prep for Class

1. Review Canvas submissions

<br>

**SLIDE**: Quick refresher on designing a project!

:::



## {background-image="Images/background-data_blue_v4.png" .center}

::: {.r-fit-text}
**Why do we need a research question?**

<br>

A research question...

- **focuses** your work,

- **drives** your progress, and

- let's you know when you're **done**.

:::

::: notes

Remember the HK reading!

1. Exploring data without a question can help you find patterns but not help you to understand why things happen
    - e.g. data mining

2. Without a disciplined research question, there’s no reason not to just check everything! 
    - Something is going to pop up as related by random chance if you check enough stuff.

:::



## {background-image="Images/background-data_blue_v4.png" .center}

::: {.r-fit-text}
**A "Good" Research Question:**

1. Can be answered,

2. Improves our understanding of the world, and

3. Is informed by the HK criteria

    - e.g. consider results, feasibility, scale and design

:::

::: notes

**Everybody remember our criteria for a good question?**

- **Consider Potential Results**: "If you can’t say something interesting about your potential results, that probably means your research question and your theory aren’t as closely linked as you think!"

- **Consider Feasibility**: "A research question should be a question that can be answered using the right data, if the right data is available. But is the right data available?"
    - You picked the data project first so this should be done!

- **Consider Scale**: "What kind of resources and time can you dedicate to answering the research question? ... Given the confines of, say, a term paper, you could take some wild swings at that question, but you’re likely to do a much more thorough job answering questions with a lot less complexity."

- **Consider Design**: "So, an important part of evaluating whether you have a workable research question is figuring out if there’s a reasonable research design you can use to answer it. Figuring out whether you do have a reasonable research design is the topic of the rest of this book."

- **Keep It Simple!**: "Answering any research question can be difficult. Don’t make it even harder on yourself by biting off more than you can chew!"

<br>

**Alright, let's hear your ideas!**

- *ON BOARD and DISCUSS*

:::



## {background-image="Images/background-data_blue_v4.png" .center}

::: {.r-fit-text}
**For Next Class: Analyzing the Second Codebook**
:::

<br>

1. Analyzing the Data Project Overall

    - What are the strengths and weaknesses of the overall data project? What variables should we consider using?
    
2. Analyzing the Selected Outcome 

    - What are the strengths and weaknesses of the specific variable we have chosen as our key outcome to explain? 

::: notes

For Monday we all need to analyze the Codebook!

- The prompts are a little more detailed on Canvas, but these are the general ideas

<br>

**Any questions on the assignment?**

:::


