---
format: revealjs
---

## Today's Agenda {background-image="Images/background-data_blue_v4.png" .center}

```{r}
#  background-size="1920px 1080px"
library(tidyverse)

```

<br>

::: {.r-fit-text}

**Developing Report 2**

- Premise 1: Making an importance argument

- Premise 2: Auditing the data

:::

<br>

::: r-stack
Justin Leinaweaver (Spring 2025)
:::

::: notes
Prep for Class

1. Check the Canvas submissions

2. Update slides BEFORE class with research questions and variable names 

<br>

For today I asked each of you to come to class with material for Section 1 and having audited the dataset.

<br>

**Everybody ready to go with these?**

<br>

**SLIDE**: Let's start with the Premise 1 evidence
:::



## Report 2 {background-image="Images/background-data_blue_v4.png" .center}

**What do we learn about the world from analyzing the Environmental Performance Index (EPI) produced by the Yale Center for Environmental Law & Policy?**

<br>

**Premise 1: Why is this project important?**

- What problem are the researchers trying to solve?

- How does the problem impact the real world?

- Why should we take these researchers seriously?
 
- How has the project impacted the world?

::: notes
Here is the general advice I offered you in week 3 for the kinds of elements that help construct an argument about importance.

- My hope is the evidence you found for today will help everyone in class make this a compelling and well supported argument!

<br>

Let's go around the room so you can each briefly introduce the evidence you found and how you think it helps us make this argument.

- *PRESENT and DISCUSS each*

<br>

An excellent jump-start on Section 1.

- **Any questions before we jump to auditing the data?**
:::



## Report 2 {background-image="Images/background-data_blue_v4.png" .smaller .center}

<br>

::: {.r-fit-text}

**Load and Examine the Structure of the Data**

:::: {.incremental}

- How are the observations organized?

- What are the variables?

- How is missing data coded?

- Any missing data concerns?

::::

:::

::: notes

Let's go back to our work on Premise 2 of the report

- Everybody import the data and get ready to explore!

<br>

The codebook gives us vital information about how the researchers actually measure the world

- BUT, that's only ONE source of uncertainty

- Data sources and weaknesses in the measurement instrument can often only be spotted once you begin to explore the data itself

<br>

**REVEAL x 4**: *Step through the questions on the slide and DISCUSS*

<br>

**SLIDE**: Let's shift to the data analysis piece of your reports

:::



## Report 2 {background-image="Images/background-data_blue_v4.png" .center}

**What do we learn about the world from analyzing the Environmental Performance Index (EPI) produced by the Yale Center for Environmental Law & Policy?**

<br>

### **Premise 3**

- **What do we learn about the current world from analyzing the most recently available data?**

    - All indicators and index (2024)

::: notes

Ok everybody, let's build a big list of tools that could help us answer this question

- So, focused on the 2024 data, what specific visualizations or descriptive statistics could we make?

<br>

*ON BOARD: Make a table*

- Columns: Variables

- Rows: Histogram, Box plot, Mean, SD, Min, Max

<br>

**SLIDE**: Alright now let's do Premise 4

:::



## Report 2 {background-image="Images/background-data_blue_v4.png" .center}

**What do we learn about the world from analyzing the Environmental Performance Index (EPI) produced by the Yale Center for Environmental Law & Policy?**

<br>

### **Premise 4**

- **What do we learn about the trajectory of environmental quality in the world from analyzing the data across time?**

    - Each indicator (1995 - 2022)

::: notes

Per EPI:

- Can I assemble the releases of the EPI into a time series or panel dataset?

- No. Because the underlying methodology and data change between versions of the EPI, it is not appropriate to assemble the scores from each release into a time series. If you wish to analyze longitudinal data on environmental performance, historic time series for many indicators are available on our downloads page.

- So, zip file on Canvas has data on each indicator across time (1995 - 2022)

<br>

Ok everybody, let's build a big list of ideas that could help us answer this question

- So, focused on the indicator data, what specific visualizations or descriptive statistics could we make?

<br>

*ON BOARD: Make a table*

- TBD

<br>

**SLIDE**: There's our plan, let's get to work!

:::




## Next Class {background-image="Images/background-data_blue_v4.png" .center}

<br>

::: {.r-fit-text}

**Outline your Planned Analyses**

1. Build all of the brainstormed analyses

2. Reflect on what you've built, and

3. Submit to Canvas your plan for Premises 3 and 4

:::

::: notes

Submit your plan to Canvas!

<br>

Canvas Assignment: Outline your Planned Analyses

Submit to Canvas a DESCRIPTION (not the actual visualizations or results) of the components you plan to include in your report.

1. What are the specific visualizations and descriptive statistics you plan on including in Premise 3 of your report? Explain EACH and the WHY you are choosing to include these tools.

2. What are the specific visualizations and descriptive statistics you plan on including in Premise 4 of your report? Explain EACH and the WHY you are choosing to include these tools.

:::





















