---
format: revealjs
---

# Today's Agenda {background-image="libs/Images/background-data_blue_v3.png"}

```{r}
#  background-size="1920px 1080px"
library(tidyverse)
library(readxl)
```

```{=html}
<style type="text/css">
    :root {
        --r-main-font-size: 45px;
    }
</style>
```
<br>

Finish the Second Report

<br>

<br>

::: r-stack
Justin Leinaweaver (Spring 2024)
:::

::: notes
Prep for Class

1. TBD
:::


## Report 2 {background-image="libs/Images/background-blue_triangles2.png"}

<br>

**Submission Requirements**

- Submit a **pdf** to **Canvas** (due **Mar 26th**)

- Include an **APA** formatted bibliography

- Polish **all** included visualizations

::: notes

?

:::



## Report 2 {background-image="libs/Images/background-blue_triangles2.png"}

<br>

**Analyzing our Predictor Variable(s)**

1. What is it and why is this project important?

2. How confident should we be in the methodology?

3. What do the measures currently show us?

4. How are these measures changing across time?

::: notes

1. In Section 1 your job is to give the reader a crash course in the chosen data project: What is it, who is behind it and why is it important?

2. Section 2 should step through the strengths and weaknesses of the measurements in the project.

3. Section 3 should focus on the most recent year available in the dataset and present a univariate analysis of it.

4. Section 4 should present univariate analyses at different snapshots in time so we can analyze the trends in the data

### Questions on the sections?

:::






