---
format: revealjs
---

## Today's Agenda {background-image="Images/background-data_blue_v4.png" .center}

```{r}
library(tidyverse)
library(readxl)
```

<br>

**What do we learn about the world from analyzing the X produced by Y?**

- Finish and submit the second report

<br>

::: r-stack
Justin Leinaweaver (Spring 2025)
:::

::: notes
Prep for Class

1. Check Canvas submissions
:::



## {background-image="Images/background-data_blue_v4.png" .center}

::: {.r-fit-text}
**Report 2**

**Analyzing our Second Data Project**
:::

1. FINAL paper due Mar 16th

2. PDFs only

3. Support ALL claims with evidence
    - APA formatted in-text citations
    - APA formatted bibliography
    
4. Report should be concise and focused on your arguments
    
::: notes

Same basic requirements as the first report

- HOWEVER, no draft this time, just the real deal!

- We've already done this once so this should be much easier the second time

<br>

**SLIDE**: Big picture aim

:::


## Report 2 {background-image="Images/background-data_blue_v4.png" .center}

<br>

**What do we learn about the world from analyzing the XX produced by YY?**

<br>

The reader of your report is a non-expert in data analysis and is not familiar with this particular project, but is very interested in the topic. 

::: notes

**Any questions on the big picture framing of your report?**

<br>

**SLIDE**: Report components

:::



## Report 2 {background-image="Images/background-data_blue_v4.png" .center}

<br>

**What do we learn about the world from analyzing the XX produced by YY?**

1. The importance of the project in the real-world,
2. The key contributors of uncertainty in the project's data,
3. What we learn about the current world from analyzing the most recently available data, and
4. What we learn about the trajectory of XX in the world from analyzing the data across time

::: notes

In terms of structure and expectations it mirrors the work you did for the first report

- **Any questions on the report?**

<br>

Rest of today is yours to work.

- Let's go!

<br>

After the break we dive into learning the tools we need to actually answer our research question!

:::


