---
format: revealjs
---

# Today's Agenda {background-image="libs/Images/background-data_blue_v3.png"}

```{r}
#  background-size="1920px 1080px"
library(tidyverse)
library(readxl)

d <- read_excel("../../Course_History/2023-Spring/Project-SP23/PREDICTOR-Government_Spending/Project_Predictors-WDI-2008_2020.xlsx", na = "NA")
```

```{=html}
<style type="text/css">
    :root {
        --r-main-font-size: 45px;
    }
</style>
```
<br>

Build the Second Report

- Section 3: Univariate Analyses (Current)

<br>

::: r-stack
Justin Leinaweaver (Spring 2024)
:::

::: notes
Prep for Class

1. Make sure all data available on Canvas

2. Post Section 3 assignment details on Canvas
:::




## Report 2 {background-image="libs/Images/background-blue_triangles2.png"}

<br>

**Submission Requirements**

- Submit a **pdf** to **Canvas** (due **Mar 26th**)

- Include an **APA** formatted bibliography

- Polish **all** included visualizations

::: notes

Ok, this week we work on your second report.

- The basic requirements same as last time

- Late penalty (-10) points per day

:::



## Report 2 {background-image="libs/Images/background-blue_triangles2.png"}

<br>

**Analyzing our Predictor Variable(s)**

1. What is it and why is this project important?

2. How confident should we be in the methodology?

3. What do the measures currently show us?

4. How are these measures changing across time?

::: notes

1. In Section 1 your job is to give the reader a crash course in the chosen data project: What is it, who is behind it and why is it important?

2. Section 2 should step through the strengths and weaknesses of the measurements in the project.

3. Section 3 should focus on the most recent year available in the dataset and present a univariate analysis of it.

4. Section 4 should present univariate analyses at different snapshots in time so we can analyze the trends in the data

### Questions on the sections?

<br>

Plan of Attack:

- Today we'll make our visualizations for Section 3

- Wednesday we'll make our visualizations for Section 4.

- Friday we'll polish it all up
:::



## For Today {background-image="libs/Images/background-blue_triangles2.png"}

<br>

Make a histogram and a map for each measure in 2019:

- Military expenditure (% of GDP)

- Current health expenditure (% of GDP)

- Government expenditure on education, total (% of GDP)

::: notes

**Don't polish until after you have these six visualizations built!**

<br>

**SLIDE**: In the report...

:::


## Report 2 {background-image="libs/Images/background-blue_triangles2.png"}

**Analyzing our Predictor Variable(s)**

<br>

**Section 3: What do the measures currently show us?**

Side-by-side plots (2019): Histogram and Map

- Fig 1a & 1b: Military expenditure
- Fig 2a & 2b: Current health expenditure
- Fig 3a & 3b: Government expenditure on education
]

::: notes

Assignment for Wednesday: Polish these up!

:::





