---
format: revealjs
---

# Today's Agenda {background-image="libs/Images/background-data_blue_v3.png"}

```{r}
library(tidyverse)
library(readxl)
library(kableExtra)
library(modelsummary)
library(ggeffects)
```

<br>

<br>

::: {.r-fit-text}
**Working on Report 3**

- Scatterplots, correlations and simple OLS regressions
:::

<br>

<br>

::: r-stack
Justin Leinaweaver (Spring 2024)
:::

::: notes
Prep for Class

1. Make sure merged data available on Canvas

2. Post assignment details on Canvas

<br>

**SLIDE**: Ok, this week we work on your third report so let's talk about it.
:::



## Report 3 {background-image="libs/Images/background-slate_v2.png" .center}

**Bivariate Test of your Hypotheses**

<br>

This report should focus on making a single, over-arching argument that answers this question: Are powerful states more likely to respect the human rights of their citizens?

::: notes
Report 3 is your first chance to try and answer our research question

- This is possible in an effective way because of the work you have done in the first two reports
:::



## Report 3 {background-image="libs/Images/background-slate_v2.png" .center}

**Bivariate Test of your Hypotheses**

<br>

**Are powerful states more likely to respect the human rights of their citizens?**

1. Analyze the relationship between a country's `cinc` score (CoW NMC) and its measured level of respect for human rights and the rule of law (FFP) **using a scatter plot, a correlation and a simple OLS regression**. 

2. Repeat the above using the CoW NMC **indicator you were assigned in Report 2** instead of the `cinc` score.

::: notes
In order to answer our research question you will perform two tests on **ALL** of the data

- cinc x p3_human_rights

- a selected NMC indicator x p3_human_rights

<br>

**Questions on prompts?**

<br>

**SLIDE**: Notes for the report
:::



## Report 3 {background-image="libs/Images/background-slate_v2.png" .center}

**Bivariate Test of your Hypotheses**

<br>

**Submission Requirements**

- Submit a **pdf** to **Canvas** (due **Apr 5th**)

- Include an **APA** formatted bibliography

- Polish **all** included visualizations and tables

- Lead with **arguments** NOT evidence

::: notes
The basic requirements same as last time

- Late penalty (-10) points per day

<br>

Important note 1: Make sure to lead all paragraphs in the paper with your argument and not with the evidence.

- Explain your argument and support it with the evidence, not vice versa.

<br>

**Questions on these elements?**

<br>

**SLIDE**: Important note 2...
:::



## Evaluating the Fit of an OLS Regression {background-image="libs/Images/background-slate_v2.png" .center}

<br>

1. Missing data problems?

2. Are the coefficients significant?

3. What does the R<sup>2</sup> indicate? 

4. Any problems in the residuals plot?


::: notes
Important note 2: Be sure to evaluate all OLS regressions you include using the four steps reviewed in class. 

<br>

These four steps allow you to explain how confident you are in the answers provided by the OLS regression.
:::



## Report 3 {background-image="libs/Images/background-slate_v2.png" .center}

**Bivariate Test of your Hypotheses**

<br>

**Are powerful states more likely to respect the human rights of their citizens?**

1. Analyze the relationship between a country's `cinc` score (CoW NMC) and its measured level of respect for human rights and the rule of law (FFP) **using a scatter plot, a correlation and a simple OLS regression**. 

2. Repeat the above using the CoW NMC **indicator you were assigned in Report 2** instead of the `cinc` score.

::: notes
Alright, let's get to work!

- Let me know if you have questions
:::

