---
format: revealjs
---

# Today's Agenda {background-image="libs/Images/background-data_blue_v3.png"}

```{r}
library(tidyverse)
library(readxl)
library(kableExtra)
library(modelsummary)
library(ggeffects)
```

<br>

<br>

**Working on Report 3**

- Scatterplots, correlations and simple OLS regressions

<br>

<br>

::: r-stack
Justin Leinaweaver (Spring 2024)
:::

::: notes
Prep for Class

1. TBD
:::



## Report 3 {background-image="libs/Images/background-slate_v2.png" .center}

**Bivariate Test of your Hypotheses**

<br>

**Submission Requirements**

- Submit a **pdf** to **Canvas** (due **Apr 5th**)

- Include an **APA** formatted bibliography

- Polish **all** included visualizations and tables

- Lead with **arguments** NOT evidence

::: notes

Ok, this week we work on your second report.

- The basic requirements same as last time

- Late penalty (-10) points per day
:::



## Report 3 {background-image="libs/Images/background-slate_v2.png" .center}

**Bivariate Test of your Hypotheses**

<br>

**Are powerful states more likely to respect the human rights of their citizens?**

1. Analyze the relationship between a country's `cinc` score (CoW NMC) and its measured level of respect for human rights and the rule of law (FFP) **using a scatter plot, a correlation and a simple OLS regression**. 

2. Repeat the above using the CoW NMC **indicator you were assigned in Report 2** instead of the `cinc` score.

::: notes
Alright, let's get to work!

- Let me know if you have questions
:::
