---
format: revealjs
---

# Today's Agenda {background-image="libs/Images/background-data_blue_v3.png"}

```{r}
library(tidyverse)
library(readxl)
library(kableExtra)
library(modelsummary)
library(ggeffects)
```

<br>

<br>

**Submit the Third Report**

<br>

<br>

::: r-stack
Justin Leinaweaver (Spring 2024)
:::

::: notes
Prep for Class

1. TBD
:::



## Report 3 {background-image="libs/Images/background-slate_v2.png" .center}

**Submission Requirements**

<br>

- Submit a **pdf** to **Canvas** (due **Mar 26th**)

- Include an **APA** formatted bibliography

- Polish **all** included visualizations and tables

::: notes

Ok, this week we work on your second report.

- The basic requirements same as last time

- Late penalty (-10) points per day
:::



## Report 3 {background-image="libs/Images/background-slate_v2.png" .center}

**Bivariate Test of your Hypotheses**

<br>

1. Introduction

2. Test hypotheses with bivariate visualizations and statistics

3. Test hypotheses with simple OLS regressions

::: notes
Next report has three required sections.
:::



## Report 3 {background-image="libs/Images/background-slate_v2.png" .center}

**Bivariate Test of your Hypotheses**

<br>

1. Introduction
    - Research Question?
    - Why is it important?
    - What are your three hypotheses?

2. Test hypotheses with bivariate visualizations and statistics

3. Test hypotheses with simple OLS regressions

::: notes

Section 1: Introduction
- What is the research question?
- Make an argument: Why should we care?
- What are your hypotheses? List all three
:::



## Report 3 {background-image="libs/Images/background-slate_v2.png" .center .smaller}

**Bivariate Test of your Hypotheses**

<br>

1. Introduction

2. Test hypotheses with bivariate visualizations and statistics
    - 2019 only
    - Scatterplots and correlations
        - GII x military
        - GII x education
        - GII x health

3. Test hypotheses with simple OLS regressions

::: notes

This is what we worked on in class last Friday.

<br>

Section 2: Test your hypothesis using bivariate visualizations and statistics

- Make a scatterplot AND calculate the correlation for each (2019 only):
    - GII x military
    - GII x education
    - GII x health
:::
    
    
    
## Report 3 {background-image="libs/Images/background-slate_v2.png" .center .smaller}

**Bivariate Test of your Hypotheses**

<br>

1. Introduction

2. Test hypotheses with bivariate visualizations and statistics

3. Test hypotheses with simple OLS regressions
    - 2019 only
    - Fit, interpret and evaluate each regression
        - GII ~ military
        - GII ~ education
        - GII ~ health

::: notes

Today's work!

Section 3: Test your hypothesis using simple OLS regressions

- Fit, interpret and evaluate three simple OLS regressions (2019 only)
::: 
