---
format: revealjs
---

## Today's Agenda {background-image="Images/background-data_blue_v4.png" .center}

```{r}
library(tidyverse)
library(readxl)
library(kableExtra)
library(modelsummary)
library(ggeffects)
```

<br>

::: {.r-fit-text}

**Thinking Carefully About Causal Inference**

- Add confounders to our research project dataset

:::

<br>

::: r-stack
Justin Leinaweaver (Spring 2025)
:::

::: notes
Prep for Class

1. Review identification DAG submissions

2. Send out data links:
    - WDI: [LINK](https://databank.worldbank.org/source/world-development-indicators)
    - Class spreadsheet: [LINK](https://docs.google.com/spreadsheets/d/1qLZjrK1QCzzX7W8TIUduyIdcCXSpPP-2r9DxI7VqQwk/edit#gid=0)
    
3. AFTER class
    
    - Grab confounders and post for class to explore 
    
    - Merge confounders onto research project dataset
    
    - Update slides 13-1 with histograms for the confounders
    
    - Update slides 13-2 with list of possible confounders
    
:::



## For Today {background-image="Images/background-data_blue_v4.png" .center}

<br>

::: {.r-fit-text}

Submit a DAG for our research project

- Press Freedom &#8594; Environmental Quality

:::

::: notes

*ON BOARD*

Let's get all three proposed DAGs on the board.

- Everybody add their proposed confounders as a list under each DAG

<br>

*PRESENT and DISCUSS each*

Let's narrow this down!

- For ease of our final reports, let's aim for one confounder for each DAG (or two max) 

:::


## {background-image="Images/12_3-WDI_Database.png" background-size='85%'}

::: notes

Data search time!

- Let's see if we can find good options on the WDI database

- If not there then we can consult the class data spreadsheet

<br>

I will merge the confounders onto our data files and we'll start working with multivariate analyses on Monday.

<br>

**SLIDE**: Assignment for next class

:::



## For Next Class {background-image="Images/background-data_blue_v4.png" .center}

<br>

**Review the Methodology and Data for the Confounders**

1. Evaluate the methodology underpinning each variable

2. Analyze each variable on its own (univariate analysis)

::: notes

Canvas has the prompts

<br>

Your assignment for Monday is to review the methodology and the data for the confounders we have selected to consider in class.

1. For each variable, examine the details provided by the World Bank (and follow the links to whomever actually produced each measure) on who produced it and how they did so then report back:

Does the variable accurately operationalize the concept we proposed as a confounder in our DAG? Why or why not?
Do you have any methodological concerns about how the variable has been constructed (e.g. instrumentation and process of measurement)?
2. Analyze each proposed confounder variable on its own (e.g. univariate analyses) and report back if you believe there is sufficient variation in the measure as to be useful in our analyses. Describe the variation in the world for each measure using complete sentences and descriptive statistics.


:::

