---
output:
  xaringan::moon_reader:
    css: ["default", "extra.css"]
    lib_dir: libs
    seal: false
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: '16:9'
---

```{r, echo = FALSE, warning = FALSE, message = FALSE}
##xaringan::inf_mr()
## For offline work: https://bookdown.org/yihui/rmarkdown/some-tips.html#working-offline
## Images not appearing? Put images folder inside the libs folder as that is the main data directory

library(tidyverse)
library(readxl)
library(stargazer)
##library(kableExtra)
##library(modelr)

knitr::opts_chunk$set(echo = FALSE,
                      eval = TRUE,
                      error = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      comment = NA)
```

class: slideblue

.size80[**Today's Agenda**]

<br>
<br>
<br>

.size40[

Wrap-up, polish and submit the research project report.

]

<br>
<br>

.center[.size40[
  Justin Leinaweaver (Fall 2021)
]]



---

class: slidepurple

.size40[**Section 1: Introduction**]
+ .size30[What is the question, why is it important and what is your argument?]

.size40[**Section 2: Bivariate Analyses**]
+ .size30[What is the answer to the question using only bivariate visualizations and simple OLS regressions?]

.size40[**Section 3: Multivariate Analyses**]
+ .size30[What is the answer to the question using multivariate visualizations and multiple OLS regressions?]

.size40[**Section 4: Conclusion**]
+ .size30[What did you find and how confident should we be in your results?]



---

class: middle, slidepurple

.size50[**Minimum Data Needs**]

.size35[
**Section 2: Bivariate Analyses**

+ Two Histograms: Outcome and Predictor
+ Scatter plot: Outcome x Predictor
+ Regression Table
]

.size35[
**Section 3: Multivariate Analyses**

+ Histogram: Confounder
+ Scatter plot: Outcome x Predictor x Confounder
+ Multiple Regression Table
+ Marginal Effects Plot
]







