---
format: revealjs
---

# Today's Agenda {background-image="libs/Images/background-data_blue_v3.png"}

```{r}
library(tidyverse)
library(readxl)
library(kableExtra)
library(modelsummary)
```

<br>

<br>

**Build the Final Report**

<br>

<br>

::: r-stack
Justin Leinaweaver (Spring 2024)
:::

::: notes
Prep for Class

1. ...

<br>

1. IDEA Evals today
    - Update link in slides
    - Schedule Canvas announcement to go out at start of class

<br>

*Email*

PLSC 296: IDEA Course Evaluation Link

Morning All,

Here is the direct link to our course evaluation survey: https://drury.campuslabs.com/eval-home/direct/4294534

Thanks,

JL

:::




## IDEA Evaluations {background-image="libs/Images/background-slate_v2.png" .center}

https://drury.campuslabs.com/eval-home/direct/4294534

::: notes
TBD
:::




## Report 4 {background-image="libs/Images/background-slate_v2.png" .center}

<br>

- Submit a **pdf** to **Canvas** (due **May 11th, 12:20p**)

- Include an **APA** formatted bibliography

- Polish **all** included visualizations and tables
]

::: notes
TBD
:::



## Report 4 {background-image="libs/Images/background-slate_v2.png" .center}

**The Research Paper**

<br>

1. Introduction

2. Theory

3. Methodology

4. Analysis

5. Conclusion

::: notes
Your final report pulls together the best work you've done from the semester into a single, stand-alone answer of the research question.

- This is the report you could hand someone interested in this topic to show them what you've learned about global gender inequality.

<br>

Each of these sections should make a short, but complete, argument.

- This doesn't have to be long, but each section should be written in essay form (e.g. complete paragraphs, clear topic sentences, etc.)

- Think of this like a highly curated selection of the work you've done this semester.
:::



## Report 4 {background-image="libs/Images/background-slate_v2.png" .center}

<br>

1. Introduction

- What is your research question?

- Why is it important?

::: notes
Don't forget the evidence for that second part!

- Real-world illustrations, prior research findings, etc.
:::



## Report 4 {background-image="libs/Images/background-slate_v2.png" .center}

<br>

2) Theory

- What is your theoretical argument?
    - e.g. explain the hypotheses

- What is your identification strategy?
    - e.g. explain the confounders

::: notes
TBD
:::



## Report 4 {background-image="libs/Images/background-slate_v2.png" .center}

<br>

3) Methodology

- What are the sources of your data?

- What concerns or limitations should we be aware of when using them?

::: notes
TBD
:::




## Report 4 {background-image="libs/Images/background-slate_v2.png" .center}

<br>

4) Analysis

- Univariate Analysis: Outcome Variable

- Test Each Hypothesis with the Data:
    - Bivariate Analysis
    
    - Multivariate Analysis

::: notes
Your analysis section should begin with a discussion of the outcome variable on its own.

- e.g. What is the "thing" you are trying to explain?

- Describe and analyze the variation in the outcome variable

<br>

After that you should focus on each hypothesis separately.

- Answer your research question using a bivariate analysis, THEN

- Check to see if the answer "survives" using a multivariate analysis.

<br>

The bivariate analysis tells us if there is an association between the variables.

The multivariate analysis tells is if we have evidence of a causal relationship between the variables.

:::




## Report 4 {background-image="libs/Images/background-slate_v2.png" .center}

<br>

5) Conclusion

- What do we learn from this project?

- Make at least one recommendation of what future research could do to advance our knowledge of this subject.

::: notes
TBD
:::




## Report 4 {background-image="libs/Images/background-slate_v2.png" .center}

<br>

1. Introduction

2. Theory

3. Methodology

4. Analysis

5. Conclusion

::: notes
**Questions on the final report?**
:::




