---
format: revealjs
---

## PLSC 296: Learning Outcomes {background-image="Images/background-data_blue_v4.png" .center}

+ **Methods Knowledge**: Students should demonstrate an ability to use statistical software to organize, explore and visualize data in order to answer important political science questions.

+ **Critical Thinking and Problem Solving Skills**: Students should demonstrate an understanding of how research design impacts our confidence in the claims made by researchers, politicians and the media.

+ **Communication Skills**: Students should demonstrate effective written and data visualization skills.

::: notes
Prep for Class

1. So much stuff... Design the final exam qs and upload all materials to Canvas

2. Be ready to publish Q1 on Canvas

<br>

Here are our learning outcomes for this class

- I need to assess how much progress each of you has made on our class LOs

- Over our final four classes together (this week plus the final exam window) you will complete four small exercises

- Each exercise asks you to answer a research question

- Your job will be to answer that question while showing me your progress on these LOs

<br>

**Important Keys to the Assessment:**

<br>

**FIRST, these are in-class exercises and you must submit your work before the end of class**

- No late submissions will be accepted

<br>

**SECOND, these are individual assessments**

- You may NOT work on these assignments with anyone else

- However, these are open note exercises!

- I am trusting you to NOT collaborate in any way during your work.

<br>

**FINALLY, you are writing for a professional, non-expert audience.**

- This means you must fully explain and support your ideas

- Write in complete sentences, and 

- Cite your evidence with in-text citations

<br>

**Big picture questions?**

<br>

Ok, Q1 is now available on Canvas

- Let's get to work!

:::



