---
format: revealjs
---

# Today's Agenda {background-image="libs/Images/background-data_blue_v3.png"}

```{r}
library(tidyverse)
library(readxl)
library(kableExtra)
library(modelsummary)
```

<br>

<br>

**Build the Final Report**

<br>

<br>

::: r-stack
Justin Leinaweaver (Spring 2024)
:::

::: notes
Prep for Class

1. ...

<br>

:::





## Report 4 {background-image="libs/Images/background-slate_v2.png" .center}

<br>

- Submit a **pdf** to **Canvas** (due **May 11th, 12:20p**)

- Include an **APA** formatted bibliography

- Polish **all** included visualizations and tables
]

::: notes
TBD
:::



## Report 4 {background-image="libs/Images/background-slate_v2.png" .center}

**The Research Paper**

<br>

1. Introduction

2. Theory

3. Methodology

4. Analysis

5. Conclusion

::: notes
Your final report pulls together the best work you've done from the semester into a single, stand-alone answer of the research question.

- This is the report you could hand someone interested in this topic to show them what you've learned about global gender inequality.

<br>

Each of these sections should make a short, but complete, argument.

- This doesn't have to be long, but each section should be written in essay form (e.g. complete paragraphs, clear topic sentences, etc.)

- Think of this like a highly curated selection of the work you've done this semester.
:::







