---
format: revealjs
---

# Today's Agenda {background-image="Images/background-data_blue_v4.png"}

```{r}
library(tidyverse)
library(readxl)
library(kableExtra)
library(modelsummary)
```

<br>

::: {.r-fit-text}
**Report 4: Multivariate test of the mechanism**
:::

<br>

::: r-stack
Justin Leinaweaver (Spring 2025)
:::

::: notes
Prep for Class

1. TBD

:::


## Report 4 {background-image="Images/background-slate_v2.png" .center}

::: {.r-fit-text}
**Multivariate test of the mechanism**
:::

<br>

**Are powerful states more likely to respect the human rights of their citizens?**

- Use all of the data

- Focus on CINC (not the indicators)



## Report 4 {background-image="Images/background-slate_v2.png" .center}

::: {.r-fit-text}
**The body of the paper must...**
:::

1. Explain your theoretical argument

2. Explain your identification strategy

3. Evaluate the quality of the data

4. Analyze the outcome variable

5. Analyze the mechanism using multivariate regressions AND visualizations




## Report 4: Notes {background-image="Images/background-slate_v2.png" .center}

- Submit a **pdf** to **Canvas** (due **May 8th, 12:20p**)

- All figures and tables in the paper must be **polished** (e.g. presentation ready)

- All regressions must be evaluated using **all of the steps** reviewed in class

- Lead all paragraphs with **ideas**, NOT with evidence

- You must support **all assertions of fact** in the paper with cited evidence or data analysis (including an APA bibliography)